### ISSUE TITLE
remove datastring references from readme

### ISSUE THREAD

**Issue by jacobrosenthal** [garrows/browser-serialport#17]
datastring has been depreciated as its not in node-serialport

**Comment by jacobrosenthal** [comment]
Use node-serial's readme with just changes where chrome doesnt support the same options?

**Comment by jacobrosenthal** [comment]
Not perfect, but maybe enough to get us going. Pulled demo from readme as its currently broken, added node-serials Use section and struck through options not available on browser-serialport
https://github.com/garrows/browser-serialport/blob/readme/README.md

I could still see a compat section that lists what we know as incompat?

**Comment by jacobrosenthal** [comment]
Actually I dont know that chrome wont support nonstandard baud rates. Docs say 'should' match standard rates such as.. And Chris uses same language 'should' so utilizing same baud list.

Added a known incompatibilities list which makes me about comfortable publishing 2.0.0

**Comment by phated** [comment]
Readme is updated
