### ISSUE TITLE
Failure to connect to port

### ISSUE THREAD

**Issue by ClausM** [garrows/browser-serialport#37]
When I start my chrome app 
1) sometimes I get a failure to connect error
2) and sometimes I get a malformed header error
![connection failure](https://cloud.githubusercontent.com/assets/1188957/7138649/51f63cb2-e287-11e4-9620-b8d3825ba5cf.gif)

Are there ways to intercept these errors?  Or if I am not asking the question correctly, please tell me what information to provide?

**Comment by jacobrosenthal** [comment]
Is this a general question about Chrome Serial API?  You need to do what the error says, you haven't checked the chrome.runtime.lastError for your error and handled appropriately. See for an example https://github.com/garrows/browser-serialport/blob/master/index.js#L192-L200
